# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f62bb36b5ec7fda763a27ee1a25dc5cb8e583d5c4a17250e2b5bf742bdd4646059e002aed2417df67961c332522c1bab38e61b93ff1a309dd50e13b4693e9de3

test:
  secret_key_base: 1b77d467230d7370a5a80db5a4dc49a23007b5b803adb3af6b02ac27357c328d79a3d050b00735f8ae80ea06d630e2f9e68cd6ff5c4030cba90c984f515dc422

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 7ad98f2f045f44c9c76d0d53b4df34c723cf5731b320e9e8ff463edb4d947091a13a00a81272ee9d8c962b53175126679c0df32a7b47fdd856cb5e599daaa985
